---
- name: install cinder-data required packages
  package: name={{ item }}
  with_items: "{{ cinder.data_pkgs[ursula_os] }}"
  register: result
  until: result|succeeded
  retries: 5

- name: iscsi target framework conf dir
  file: dest=/etc/tgt/conf.d state=directory

- name: tgt config files
  template: src={{ item.value.src }} dest={{ item.value.dest }} mode=0644
  with_dict:
    targets:
      src: etc/tgt/targets.conf
      dest: /etc/tgt/targets.conf
    cinder_tgt:
      src: etc/tgt/conf.d/cinder_tgt.conf
      dest: /etc/tgt/conf.d/cinder_tgt.conf
  notify: restart tgt service

- name: ensure tgt service is running
  service: name="{{ cinder.tgt_service[ursula_os] }}" state=started

- include: volume_group.yml
  when: cinder.create_vg and ( cinder.fixed_key is not defined or (cinder.fixed_key is defined and "compute" not in group_names) )

- name: iscsi start
  service: name="{{ cinder.iscsi_service[ursula_os] }}" state=started

- name: enable cinder encryption
  template: src=etc/cinder/cinder.encryption.conf dest=/etc/cinder/cinder.encryption.conf mode=0640
            owner=root group=cinder
  notify: restart cinder services
  when: cinder.fixed_key is defined

- name: disable cinder encryption
  file: dest=/etc/cinder/cinder.encryption.conf state=absent
  notify: restart cinder services
  when: cinder.fixed_key is not defined

#When OS is Ubuntu
- block:
  - name: install cinder-volume service (ubuntu)
    upstart_service:
      name: "{{ item.name }}"
      user: "{{ item.user }}"
      cmd: "{{ item.cmd }}"
      config_dirs: "{{ item.config_dirs }}"
    with_items:
      - "{{ cinder.services.cinder_volume }}"

  - name: install cinder backup service (ubuntu)
    upstart_service:
      name: "{{ item.name }}"
      user: "{{ item.user }}"
      cmd: "{{ item.cmd }}"
      config_dirs: "{{ item.config_dirs }}"
    when: swift.enabled|default(false)
    with_items:
      - "{{ cinder.services.cinder_backup }}"
  when: ursula_os == 'ubuntu'


#When OS is Rhel
- block:
  - name: install cinder-volume service (rhel)
    systemd_service:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      type: "{{ item.type }}"
      user: "{{ item.user }}"
      cmd: "{{ item.cmd }}"
      config_files: "{{ item.config_files }}"
      restart: "{{ item.restart }}"
      kill_mode: "{{ item.kill_mode }}"
    with_items:
      - "{{ cinder.services.cinder_volume }}"

  - name: install cinder backup service (rhel)
    systemd_service:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      type: "{{ item.type }}"
      user: "{{ item.user }}"
      cmd: "{{ item.cmd }}"
      config_files: "{{ item.config_files }}"
      restart: "{{ item.restart }}"
    when: swift.enabled|default(false)
    with_items:
      - "{{ cinder.services.cinder_backup }}"
  when: ursula_os == 'rhel'

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify:
    - restart cinder services
    - restart cinder backup service
  when: (code_has_changed | default(False) and upgrade | default(False)) or
        (ceph.enabled and cephclient_upgraded|default(false))

- meta: flush_handlers

- name: start cinder-volume
  service:
    name: "{{ cinder.services.cinder_volume.name }}"
    state: started
    enabled: True
  delegate_to: "{{ item }}"
  run_once: True
  with_items: "{{ play_hosts }}"

- name: start cinder backup
  service:
    name: "{{ cinder.services.cinder_backup.name }}"
    state: started
    enabled: True
  delegate_to: "{{ item }}"
  run_once: True
  when: swift.enabled|default(false)
  with_items: "{{ play_hosts }}"

- include: monitoring.yml
  when: monitoring.enabled|default(True)
  tags:
    - monitoring
    - common
