---
- name: openstack creds
  template: src=root/stackrc dest=/root/stackrc
  when: client.write_stackrc

- name: install required packages for clients
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ client.apt_packages }}"
  register: result
  until: result|succeeded
  retries: 5
  
- name: install required packages for clients
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ client.names }}"
  register: result
  until: result|succeeded
  retries: 5
  when: ursula_os == 'rhel' and openstack_install_method == 'distro'

- name: install openstack clients
  pip: name={{ item }}
  with_items: "{{ client.names }}"
  notify:
    - update ca certs
  register: result
  until: result|succeeded
  retries: 5
  when: (ursula_os == 'ubuntu') or (ursula_os == 'rhel' and openstack_install_method == 'source')

- name: fix ssl certs for requests for keystone-client on trusty
  file: src=/etc/ssl/certs/ca-certificates.crt
        dest=/usr/local/lib/python2.7/dist-packages/requests/cacert.pem
        owner=root
        mode=0644 state=link force=yes
  when: ansible_distribution_version == "14.04"

- name: migrate neutron services script
  template: src=usr/local/bin/migrate_neutron_services
            dest=/usr/local/bin/migrate_neutron_services mode=0755
